---
name: pipes
tile:
  width: 3
  height: 3
borders:
  "0": "empty"
  "1": "pipe"
connectivity: 4
options:
  useBorderModule: true
borderModules:
  __border__:
    borders:
      t: [ 0 ]
      b: [ 0 ]
      l: [ 0 ]
      r: [ 0 ]
modules:
  empty:
    imageCoords: [1, 5]
    borders:
      t: [0]
      b: [0]
      l: [0]
      r: [0]
    rotations: []
  4way:
    imageCoords: [1, 1]
    borders:
      t: [1]
      b: [1]
      l: [1]
      r: [1]
    rotations: []
  3way:
    imageCoords: [1, 3]
    borders:
      t: [1]
      b: [1]
      l: [1]
      r: [0]
    rotations: [90, 180, 270]
  2waystraight:
    imageCoords: [1, 2]
    borders:
      t: [1]
      b: [1]
      l: [0]
      r: [0]
    rotations: [90]
  2waybent:
    imageCoords: [1, 4]
    borders:
      t: [1]
      b: [0]
      l: [1]
      r: [0]
    rotations: [90, 180, 270]
