---
name: pipes
tile:
  width: 3
  height: 3
borderIds:
  "0": "empty"
  "1": "pipe"
connectivity: 4
modules:
  empty:
    imageCoords: [1, 5]
    borderIds:
      top: [0]
      bottom: [0]
      left: [0]
      right: [0]
    rotations: []
  4way:
    imageCoords: [1, 1]
    borderIds:
      top: [1]
      bottom: [1]
      left: [1]
      right: [1]
    rotations: []
  3way:
    imageCoords: [1, 3]
    borderIds:
      top: [1]
      bottom: [1]
      left: [1]
      right: [0]
    rotations: [90, 180, 270]
  2waystraight:
    imageCoords: [1, 2]
    borderIds:
      top: [1]
      bottom: [1]
      left: [0]
      right: [0]
    rotations: [90]
  2waybent:
    imageCoords: [1, 4]
    borderIds:
      top: [1]
      bottom: [0]
      left: [1]
      right: [0]
    rotations: [90, 180, 270]
